### ISSUE TITLE
Outline doesn't apply to all edges

### ISSUE THREAD

**Issue by mnowatzke** [eldskald/godot4-cel-shader#3]
First off love this shader and excuse my shader ignorance, as I'd try to fix this myself first probably if I had the knowledge.
Is there a way to edit the outline shader so it applies to all edges? You can see here I have a simple box but it does not outline everything.
![image](https://github.com/user-attachments/assets/2eafb325-47d2-4270-a7ee-70062b1fa034)

**Comment by eldskald** [comment]
You can't fix these in the shader, but you can fix these in the model. The trick is to not use hard edges, bevel them instead. You can make the bevel faces very small or even with 0 area if you want and it should probably still work, just don't make models with hard edges, always stay on smooth mode.

But still, I would say stay away from completely flat surfaces all together, it's not just the outlines but the whole "all or nothing" shading style of cel shaders make them look potentially weird when moving around in a light source. I can tell that this cube in the photo isn't cel shaded because each face has a different shade, the cel shader would make half of the faces bright and the other half dark, supposing there is just one light source in this scene. It's not a big problem, it just means that if this cube was spinning around, it would have its faces flashing suddenly from dark to bright with little smoothing. You can increase the smoothing in the `diffuse_curve` texture to make it better, but be aware that it would affect all models.

**Comment by mnowatzke** [comment]
Thanks for the reply! This is extremely helpful. I'll make the necessary changes. Again, great work overall.

And @TranquilMarmot I tried to use that shader as well but there is some bug with the vertices on GridMap that cause all sorts of visual glitchiness (not just with that specific post-process shader but other items too...).
